openapi_token: "OPENAI_TOKEN"
openapi_model: "gpt-3.5-turbo"
attempt_limit: 10

discord_bot_token: "DISCORD_BOT_TOKEN"

discord_log_path: "bot.log"
db_log_path: "bot.log"

db_path: "postgresql://USERNAME:PASSWORD@IP/DB_NAME"


hour_message_limit: 20